version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    ignore:
      - dependency-name: "*"
        versions: ["*"]
